title: "CalvinIO"
author: "Calvin"
description: "Really cool blog about ... something"
permalink: /:year/:month/:day/:title.html
lang: "en"

dark_header: true            # keep the header dark
dark_footer: false           # keep the footer dark
dark_theme: false            # use the dark mode as default
show_footer: false           # show the "previous" and "next" links at the end of each post
hide_title: false            # don't show the site title in the header
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  - about.md
  - presentation.md

icons: # icons in the header, see http://fontawesome.com/icons         
  # info-circle: "/about"
  # desktop: "/presentation"
  medium: "https://medium.com/@canhtran" 
  envelope: "mailto:trandcanh@gmail.om"
  github: "https://github.com/canhtran"
  rss: "/feed.xml"

comments:                    # embed disqus or isso comments
  disqus: "calvinio-com"
#  isso: ""

plugins:
  - jekyll-feed
  - jekyll-default-layout
